# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---

CI 🤖:
  - changed-files:
      - any-glob-to-any-file: [".github/**", "tools/**"]

root:
  - changed-files:
      - any-glob-to-any-file: "*"

vm-provisioning:
  - changed-files:
      - any-glob-to-any-file: "vm-provisioning/**"
