# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

all: lint

lint:
	tflint --init --recursive
	tflint --recursive

dependency-check:
	@# Help: Does nothing.
	@echo "Does nothing."

build:
	@# Help: Does nothing.
	@echo "Does nothing."