---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Stale Pull Requests

# After 30 days of no activity on a PR, the PR should be marked as stale,
# a comment made on the PR informing the author of the new status,
# and closed after 15 days if there is no further activity from the change to stale state.
on:
  schedule:
    - cron: '30 1 * * *'  # run every day
  workflow_dispatch: {}

permissions: {}

jobs:
  stale-auto-close:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
      - uses: actions/stale@3a9db7e6a41a89f618792c92c0e97cc736e1b13f  # v10.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: 'This pull request is stale because it has been open 30 days with no activity. Make a comment or update the PR to avoid closing PR after 15 days.'
          days-before-pr-stale: 30
          days-before-pr-close: 15
          remove-pr-stale-when-updated: 'true'
          close-pr-message: 'This pull request was automatically closed due to inactivity'
