---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Pre-Merge CI Pipeline

on:
  pull_request:
    branches:
      - main
      - release-*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  pre-checks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    outputs:
      filtered_projects: ${{ steps.filter-changes.outputs.filtered_projects }}
      other_changed_projects: ${{ steps.filter-changes.outputs.other_changed_projects }}
      artifact_path: ${{ steps.arti-path.outputs.artifact_path }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: "Verify Branch Name"
        uses: open-edge-platform/orch-ci/verify-branch-name@5f1c7f544b235db6ded508b6b4c6a2d3a78a38be # v0.1.45
      - name: "Discover Changed Subfolders"
        id: discover-changes
        uses: open-edge-platform/orch-ci/discover-changed-subfolders@5f1c7f544b235db6ded508b6b4c6a2d3a78a38be # v0.1.45
      - name: "Filter Out Unwanted Changed Subfolders"
        id: filter-changes
        env:
          changed_projects: ${{ steps.discover-changes.outputs.changed_projects }}
        run: |
          folders_to_remove='[".github",".reuse","LICENSES",".git","tools",""]'
          filtered_projects=$(echo "$changed_projects" | jq -cr --argjson folders_to_remove "$folders_to_remove" 'map(select(. as $item | $folders_to_remove | index($item) | not))')
          other_changed_projects=$(echo "$changed_projects" | jq -cr --argjson filtered_projects "$filtered_projects" 'map(select(. as $item | $filtered_projects | index($item) | not))')
          echo "filtered_projects=$filtered_projects" >> $GITHUB_OUTPUT
          echo "other_changed_projects=$other_changed_projects" >> $GITHUB_OUTPUT
          echo "filtered_projects=$filtered_projects" >> $GITHUB_ENV
      - name: "Artifact Folder or Files"
        id: arti-path
        run: |
          if [ "$filtered_projects" == '["vm-provisioning"]' ]; then
            echo "artifact_path<<EOF" >> $GITHUB_OUTPUT
            echo "vm-provisioning/out/" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "artifact_path=empty" >> $GITHUB_OUTPUT
          fi
  pre-merge-root:
    needs: pre-checks
    if: ${{ contains(needs.pre-checks.outputs.other_changed_projects, '.github') || contains(needs.pre-checks.outputs.other_changed_projects, '.reuse') || contains(needs.pre-checks.outputs.other_changed_projects, 'LICENSES') || contains(needs.pre-checks.outputs.other_changed_projects, '""' ) || contains(needs.pre-checks.outputs.other_changed_projects, 'tools')}}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '18'
      - run: |
          npm install -g \
          "markdownlint-cli@${{ env.MARKDOWNLINT_CLI_VER }}"
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        id: setup_python
        with:
          python-version: '3.13'
      - name: Restore cached virtualenv
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          key: venv-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}
          path: venv_infra

      - name: Run mdlint
        run: make mdlint
      - name: Run license check
        run: make license
  pre-merge-pipeline:
    needs: pre-checks
    if: ${{ needs.pre-checks.outputs.filtered_projects != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        project_folder: ${{ fromJson(needs.pre-checks.outputs.filtered_projects) }}
    uses: open-edge-platform/orch-ci/.github/workflows/pre-merge.yml@5f1c7f544b235db6ded508b6b4c6a2d3a78a38be # v0.1.45
    permissions:
      contents: read
      pull-requests: write
    with:
      run_security_scans: true
      run_version_check: true
      run_dep_version_check: true
      run_build: true
      run_lint: true
      run_test: false # only for testing
      run_validate_clean_folder: true
      run_docker_build: true
      run_artifact: true
      artifacts_path: ${{ needs.pre-checks.outputs.artifact_path }}
      prefix_tag_separator: "/"
      project_folder: ${{ matrix.project_folder }}
      trivy_config_path: '${{ matrix.project_folder }}/trivy.yaml'
    secrets:
      NO_AUTH_ECR_PUSH_USERNAME: ${{ secrets.NO_AUTH_ECR_PUSH_USERNAME }}
      NO_AUTH_ECR_PUSH_PASSWD: ${{ secrets.NO_AUTH_ECR_PUSH_PASSWD }}
  final-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    if: ${{ always() }}
    needs: [pre-merge-root, pre-merge-pipeline]
    steps:
      - name: Final Status Check
        env:
          pre_merge_root_pipeline: ${{ needs.pre-merge-root.result }}
          pre_merge_pipeline: ${{ needs.pre-merge-pipeline.result }}
        run: |
          results=("pre_merge_root_pipeline" "pre_merge_pipeline")
          status="OK"
        
          for result in "${results[@]}"; do
            pipeline_result=$(eval echo \$$result)
            echo "${result} result: $pipeline_result"
            if [[ "$pipeline_result" != "success" && "$pipeline_result" != "skipped" ]]; then
              status="KO"
            fi
          done
        
          if [[ "$status" == "OK" ]]; then
            echo "Pre-merge check passed successfully."
          else
            echo "All pre-merge checks failed or were skipped. PR can't get merged"
            exit 1
          fi
